config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class= "container">
  <%= form_with(model: article, local: true) do |form| %>
  <div class ="row justify-content-center">
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class = "col-10">
      <div class="form-group row">
        <%= form.label :title, class: "col-2 col-form-label" %>
        <div class ="col-10">
          <%= form.text_field :title, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :description, class: "col-2 col-form-label"  %>
        <div class ="col-10">
          <%= form.text_area :description, rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group justify-content-center">
        <%= form.submit class:"btn btn-outline-light btn-lg" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class = "text-center mt-4">Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
  <p id="notice"><%= notice %></p>

  <div class= "container" >
  <h1 class = "text-center">Listing all articles</h1>

  <% @articles.each do |article| %>
    <div class = "row justify-content-md-center">
      <div class= "col-8 mt-4">
       <div class="shadow  mb-5 bg-white rounded">
        <div class="card text-center">
         
            <div class= "card-header font-italic">
              by Edafe Bain
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}%>
           
            </div>
            <div class="card-footer text-muted">
              <small>Create <%= time_ago_in_words(article.created_at) %> ago, 
              Edited<%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  

app/views/articles/new.html.erb
<div id="page-content">
<h1 class = "text-center mt-4">Create New Article</h1>

<%= render 'form', article: @article %>


</div>

app/views/articles/show.html.erb
<div class= "container" >
  <h2 class = "text-center"><%= @article.title %></h2>

  
    <div class = "row justify-content-md-center">
      <div class= "col-8 mt-4">
       <div class="shadow  mb-5 bg-white rounded">
        <div class="card text-center">
         
            <div class= "card-header font-italic">
              by Edafe Bain
            </div>
            <div class="card-body">
              
              <div class="card-text text-left"><%= simple_format(@article.description, length: 100) %></div>
             
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}%>
           
            </div>
            <div class="card-footer text-muted">
              <small>Create <%= time_ago_in_words(@article.created_at) %> ago,
              Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Edafe Bainbridge Erhirhi", "https://edafebain.netlify.app" %></small>
      
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Bain Technology ", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Create New Article', new_article_path, class: "dropdown-item" %></li>
            <li><%= link_to "View Articles ", articles_path, class: "dropdown-item" %></li>
            
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BainbridgeIT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "d-flex flex-column">

    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to 'Home', pages_home_path %>

app/views/pages/home.html.erb
<div class = "container" id = "home-container">
    <div class="jumbotron text-center text-Black">
        <h1 class="display-4">Bain Technology</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
            <a class="btn btn-success btn-lg" href="#" role="button">Sign Up!</a>
        </p>
    </div>
</div>

<%
=begin%>
 <%= link_to 'About', pages_about_path %> 
<%
=end%>